# Generated by Django 5.0.2 on 2024-08-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_address1_customuser_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='zipcode',
            field=models.IntegerField(default='1000000', verbose_name='郵便番号'),
        ),
    ]
