# Generated by Django 5.0.2 on 2024-08-17 05:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joinedDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='入会日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address1',
            field=models.CharField(default='YourCity', max_length=50, verbose_name='住所1'),
        ),
        migrations.CreateModel(
            name='SubscriptionCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeCustomerId', models.CharField(max_length=255)),
                ('stripeSubscriptionId', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
